// Code generated by mcpgen. DO NOT EDIT.

package mcpapi

import "context"

type Handler interface {
	CreatePet(context.Context, CreatePetRequest) (Pet, error)
	Echo(context.Context, EchoInput) (EchoOutput, error)
	GetPet(context.Context, GetPetInput) (Pet, error)
	Search(context.Context, SearchInput) (SearchResult, error)
}

type UnimplementedHandler struct{}

func (UnimplementedHandler) CreatePet(context.Context, CreatePetRequest) (Pet, error) {
	var zero Pet
	return zero, ErrNotImplemented
}
func (UnimplementedHandler) Echo(context.Context, EchoInput) (EchoOutput, error) {
	var zero EchoOutput
	return zero, ErrNotImplemented
}
func (UnimplementedHandler) GetPet(context.Context, GetPetInput) (Pet, error) {
	var zero Pet
	return zero, ErrNotImplemented
}
func (UnimplementedHandler) Search(context.Context, SearchInput) (SearchResult, error) {
	var zero SearchResult
	return zero, ErrNotImplemented
}
