// Code generated by mcpgen. DO NOT EDIT.

package mcpapi

import (
	"context"
	"encoding/json"
	"errors"
	"github.com/modelcontextprotocol/go-sdk/jsonrpc"
	"github.com/modelcontextprotocol/go-sdk/mcp"
)

var ErrNotImplemented = ToolError{Code: "not_implemented", Message: "tool not implemented"}

type ToolError struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

func (e ToolError) Error() string                 { return e.Code + ": " + e.Message }
func NewToolError(code, message string) ToolError { return ToolError{Code: code, Message: message} }

// ToolHandlerFunc receives a tool name and its decoded generated input type.
// Return the tool's generated output type on success.
type ToolHandlerFunc func(context.Context, string, any) (any, error)
type Middleware func(ToolHandlerFunc) ToolHandlerFunc

func wrapTool(next ToolHandlerFunc, middleware []Middleware) ToolHandlerFunc {
	for i := len(middleware) - 1; i >= 0; i-- {
		next = middleware[i](next)
		if next == nil {
			return func(context.Context, string, any) (any, error) {
				return nil, errors.New("middleware returned nil handler")
			}
		}
	}
	return next
}

func adaptError(err error) error {
	var value ToolError
	if errors.As(err, &value) {
		data, _ := json.Marshal(value)
		return errors.New(string(data))
	}
	var ptr *ToolError
	if errors.As(err, &ptr) && ptr != nil {
		data, _ := json.Marshal(ptr)
		return errors.New(string(data))
	}
	return &jsonrpc.Error{Code: -32603, Message: "internal error"}
}
func registerCreatePet(server *mcp.Server, handler Handler, middleware []Middleware) {
	call := wrapTool(func(ctx context.Context, _ string, input any) (any, error) {
		typed, ok := input.(CreatePetRequest)
		if !ok {
			return nil, errors.New("middleware returned invalid input type")
		}
		return handler.CreatePet(ctx, typed)
	}, middleware)
	mcp.AddTool(server, toolCreatePet, func(ctx context.Context, _ *mcp.CallToolRequest, input CreatePetRequest) (*mcp.CallToolResult, Pet, error) {
		var zero Pet
		value, err := call(ctx, "create_pet", input)
		if err != nil {
			return nil, zero, adaptError(err)
		}
		output, ok := value.(Pet)
		if !ok {
			return nil, zero, adaptError(errors.New("middleware returned invalid output type"))
		}
		return nil, output, nil
	})
}
func registerEcho(server *mcp.Server, handler Handler, middleware []Middleware) {
	call := wrapTool(func(ctx context.Context, _ string, input any) (any, error) {
		typed, ok := input.(EchoInput)
		if !ok {
			return nil, errors.New("middleware returned invalid input type")
		}
		return handler.Echo(ctx, typed)
	}, middleware)
	mcp.AddTool(server, toolEcho, func(ctx context.Context, _ *mcp.CallToolRequest, input EchoInput) (*mcp.CallToolResult, EchoOutput, error) {
		var zero EchoOutput
		value, err := call(ctx, "echo", input)
		if err != nil {
			return nil, zero, adaptError(err)
		}
		output, ok := value.(EchoOutput)
		if !ok {
			return nil, zero, adaptError(errors.New("middleware returned invalid output type"))
		}
		return nil, output, nil
	})
}
func registerGetPet(server *mcp.Server, handler Handler, middleware []Middleware) {
	call := wrapTool(func(ctx context.Context, _ string, input any) (any, error) {
		typed, ok := input.(GetPetInput)
		if !ok {
			return nil, errors.New("middleware returned invalid input type")
		}
		return handler.GetPet(ctx, typed)
	}, middleware)
	mcp.AddTool(server, toolGetPet, func(ctx context.Context, _ *mcp.CallToolRequest, input GetPetInput) (*mcp.CallToolResult, Pet, error) {
		var zero Pet
		value, err := call(ctx, "get_pet", input)
		if err != nil {
			return nil, zero, adaptError(err)
		}
		output, ok := value.(Pet)
		if !ok {
			return nil, zero, adaptError(errors.New("middleware returned invalid output type"))
		}
		return nil, output, nil
	})
}
func registerSearch(server *mcp.Server, handler Handler, middleware []Middleware) {
	call := wrapTool(func(ctx context.Context, _ string, input any) (any, error) {
		typed, ok := input.(SearchInput)
		if !ok {
			return nil, errors.New("middleware returned invalid input type")
		}
		return handler.Search(ctx, typed)
	}, middleware)
	mcp.AddTool(server, toolSearch, func(ctx context.Context, _ *mcp.CallToolRequest, input SearchInput) (*mcp.CallToolResult, SearchResult, error) {
		var zero SearchResult
		value, err := call(ctx, "search", input)
		if err != nil {
			return nil, zero, adaptError(err)
		}
		output, ok := value.(SearchResult)
		if !ok {
			return nil, zero, adaptError(errors.New("middleware returned invalid output type"))
		}
		return nil, output, nil
	})
}
