// Code generated by mcpgen. DO NOT EDIT.

package mcpapi

import "github.com/modelcontextprotocol/go-sdk/mcp"

var toolCreatePet = &mcp.Tool{Name: "create_pet", Title: "", Description: "Create a pet.", Annotations: nil, InputSchema: schemaCreatePetInput, OutputSchema: schemaCreatePetOutput}
var toolEcho = &mcp.Tool{Name: "echo", Title: "Echo", Description: "Echo a message.", Annotations: nil, InputSchema: schemaEchoInput, OutputSchema: schemaEchoOutput}
var hintGetPetDestructiveHint = false
var hintGetPetOpenWorldHint = false
var toolGetPet = &mcp.Tool{Name: "get_pet", Title: "Get pet", Description: "Get a pet by its ID.", Annotations: &mcp.ToolAnnotations{ReadOnlyHint: true, IdempotentHint: false, Title: "", DestructiveHint: &hintGetPetDestructiveHint, OpenWorldHint: &hintGetPetOpenWorldHint}, InputSchema: schemaGetPetInput, OutputSchema: schemaGetPetOutput}
var hintSearchDestructiveHint = false
var toolSearch = &mcp.Tool{Name: "search", Title: "", Description: "Search pets by name.", Annotations: &mcp.ToolAnnotations{ReadOnlyHint: true, IdempotentHint: false, Title: "", DestructiveHint: &hintSearchDestructiveHint}, InputSchema: schemaSearchInput, OutputSchema: schemaSearchOutput}
