// Code generated by mcpgen. DO NOT EDIT.

package mcpapi

type CreatePetRequest struct {
	Kind PetKind `json:"kind"`
	Name string  `json:"name"`
}

type EchoInput struct {
	Message string `json:"message"`
}

type EchoOutput struct {
	Message string `json:"message"`
}

type GetPetInput struct {
	PetID string `json:"pet_id"`
}

type Pet struct {
	ID   string  `json:"id"`
	Kind PetKind `json:"kind"`
	Name string  `json:"name"`
}

// The pet is a cat or a dog.
type PetKind string

const (
	PetKindCat PetKind = "cat"
	PetKindDog PetKind = "dog"
)

type SearchInput struct {
	Filter *SearchInputFilter `json:"filter,omitempty"`
	Limit  *int64             `json:"limit,omitempty"`
	// Case-insensitive name substring.
	Query string           `json:"query"`
	Sort  *SearchInputSort `json:"sort,omitempty"`
}

type SearchInputFilter struct {
	IDs *[]string `json:"ids,omitempty"`
}

type SearchInputSort string

const (
	SearchInputSortRelevance SearchInputSort = "relevance"
	SearchInputSortCreatedAt SearchInputSort = "created_at"
)

type SearchResult struct {
	Pets []Pet `json:"pets"`
}
