package generate

import (
	"bytes"
	"fmt"
	"go/format"
	"go/token"
	"os"
	"path/filepath"

	"github.com/phaseant/mcpgen/internal/naming"
	"github.com/phaseant/mcpgen/internal/spec"
)

type tool struct {
	Name, Method, Input, Output string
	Spec                        *spec.Tool
}
type model struct {
	Doc          *spec.Document
	Tools        []tool
	Declarations map[string]string
	Names        map[string]string
	Err          error
}

func Generate(doc *spec.Document, pkg string) (map[string][]byte, error) {
	if !token.IsIdentifier(pkg) || token.Lookup(pkg).IsKeyword() || pkg == "_" {
		return nil, fmt.Errorf("invalid package name %q", pkg)
	}
	m := &model{Doc: doc, Declarations: map[string]string{}, Names: map[string]string{}}
	for _, name := range []string{"Handler", "Server", "ServerOption", "WithLogger", "WithMiddleware", "Middleware", "ToolHandlerFunc", "HTTPOptions", "RegisterTools", "NewServer", "ToolError", "NewToolError", "ErrNotImplemented", "UnimplementedHandler"} {
		m.Names[name] = "generated runtime"
	}
	for _, key := range spec.Keys(doc.Schemas) {
		m.claim(naming.Go(key), "schemas."+key, doc.Schemas[key])
	}
	for _, key := range spec.Keys(doc.Schemas) {
		m.emitType(naming.Go(key), doc.Schemas[key])
	}
	methods := map[string]string{}
	for _, name := range spec.Keys(doc.Tools) {
		method := naming.Go(name)
		if !token.IsIdentifier(method) || method == "" {
			return nil, fmt.Errorf("invalid tool name %q", name)
		}
		if other, ok := methods[method]; ok {
			return nil, spec.At(doc.Tools[name].Position, "tools."+name, fmt.Sprintf("method %s collides with tool %q", method, other))
		}
		methods[method] = name
		t := tool{Name: name, Method: method, Input: method + "Input", Output: method + "Output", Spec: doc.Tools[name]}
		t.Input = m.rootType(t.Input, t.Spec.Input)
		t.Output = m.rootType(t.Output, t.Spec.Output)
		m.Tools = append(m.Tools, t)
	}
	if m.Err != nil {
		return nil, m.Err
	}
	var types bytes.Buffer
	for _, key := range spec.Keys(m.Declarations) {
		types.WriteString(m.Declarations[key])
	}
	schemas, err := m.schemas()
	if err != nil {
		return nil, err
	}
	parts := map[string][]byte{
		"types.gen.go":    types.Bytes(),
		"handlers.gen.go": m.handlers(),
		"schemas.gen.go":  schemas,
		"tools.gen.go":    m.tools(),
		"server.gen.go":   m.server(),
		"runtime.gen.go":  m.runtime(),
	}
	for _, name := range spec.Keys(parts) {
		source := append([]byte("// Code generated by mcpgen. DO NOT EDIT.\n\npackage "+pkg+"\n\n"), parts[name]...)
		formatted, err := format.Source(source)
		if err != nil {
			return nil, fmt.Errorf("format %s: %w", name, err)
		}
		parts[name] = formatted
	}
	return parts, nil
}

// Write only replaces files owned by this generator.
func Write(dir string, files map[string][]byte) error {
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}
	var changed []string
	for _, name := range spec.Keys(files) {
		path := filepath.Join(dir, name)
		if info, err := os.Lstat(path); err == nil && !info.Mode().IsRegular() {
			return fmt.Errorf("refusing to overwrite non-regular file %s", path)
		}
		old, err := os.ReadFile(path)
		if err == nil {
			if bytes.Equal(old, files[name]) {
				continue
			}
			if !bytes.HasPrefix(old, []byte("// Code generated by mcpgen. DO NOT EDIT.")) {
				return fmt.Errorf("refusing to overwrite handwritten file %s", path)
			}
		} else if !os.IsNotExist(err) {
			return err
		}
		changed = append(changed, name)
	}
	for _, name := range changed {
		if err := writeFile(filepath.Join(dir, name), files[name]); err != nil {
			return err
		}
	}
	return nil
}

func writeFile(path string, data []byte) error {
	f, err := os.CreateTemp(filepath.Dir(path), ".mcpgen-*")
	if err != nil {
		return err
	}
	defer os.Remove(f.Name())
	if _, err := f.Write(data); err != nil {
		f.Close()
		return err
	}
	if err := f.Chmod(0644); err != nil {
		f.Close()
		return err
	}
	if err := f.Close(); err != nil {
		return err
	}
	return os.Rename(f.Name(), path)
}

func Check(dir string, files map[string][]byte) error {
	for _, name := range spec.Keys(files) {
		path := filepath.Join(dir, name)
		data, err := os.ReadFile(path)
		if err != nil {
			return fmt.Errorf("generated code is missing or unreadable: %s: %w", path, err)
		}
		if !bytes.Equal(data, files[name]) {
			return fmt.Errorf("generated code is stale: %s; run go generate ./...", path)
		}
	}
	return nil
}
