package generate

import (
	"bytes"
	"context"
	"flag"
	"go/ast"
	"go/parser"
	"go/token"
	"go/types"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/phaseant/mcpgen/internal/spec"
)

var update = flag.Bool("update", false, "update generated golden files")

func TestGolden(t *testing.T) {
	data, err := os.ReadFile("testdata/echo.yaml")
	if err != nil {
		t.Fatal(err)
	}
	doc, err := spec.Parse("echo.yaml", data)
	if err != nil {
		t.Fatal(err)
	}
	files, err := Generate(doc, "echoapi")
	if err != nil {
		t.Fatal(err)
	}
	for _, name := range spec.Keys(files) {
		path := filepath.Join("testdata", "golden", name)
		if *update {
			if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
				t.Fatal(err)
			}
			if err := os.WriteFile(path, files[name], 0644); err != nil {
				t.Fatal(err)
			}
		}
		want, err := os.ReadFile(path)
		if err != nil {
			t.Fatal(err)
		}
		if !bytes.Equal(want, files[name]) {
			t.Errorf("%s differs; run go test ./internal/generate -run TestGolden -update", name)
		}
	}
}

func TestDeterministicGeneration(t *testing.T) {
	data, err := os.ReadFile("../../example/mcp.yaml")
	if err != nil {
		t.Fatal(err)
	}
	var first map[string][]byte
	for i := 0; i < 20; i++ {
		doc, err := spec.Parse("mcp.yaml", data)
		if err != nil {
			t.Fatal(err)
		}
		files, err := Generate(doc, "mcpapi")
		if err != nil {
			t.Fatal(err)
		}
		if i == 0 {
			first = files
			continue
		}
		for name, source := range first {
			if !bytes.Equal(source, files[name]) {
				t.Fatalf("non-deterministic %s", name)
			}
		}
	}
}

func TestNameCollisions(t *testing.T) {
	cases := []struct{ name, input, extra, want string }{
		{"runtime", "{type: object}", "schemas: {Handler: {type: string}}", "generated runtime"},
		{"field", "{type: object, properties: {foo_bar: {type: string}, foo-bar: {type: string}}}", "", "field name collides"},
		{"enum", "{type: object, properties: {sort: {type: string, enum: [foo_bar, foo-bar]}}}", "", "collides"},
		{"nested type", "{type: object, properties: {filter: {type: object}}}", "schemas: {EchoInputFilter: {type: string}}", "collides"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			data := "mcp: '1'\ninfo: {name: test, version: '1'}\ntools:\n  echo:\n    input: " + tc.input + "\n    output: {type: object}\n" + tc.extra + "\n"
			doc, err := spec.Parse("test.yaml", []byte(data))
			if err != nil {
				t.Fatal(err)
			}
			_, err = Generate(doc, "testapi")
			if err == nil || !strings.Contains(err.Error(), tc.want) {
				t.Fatalf("error=%v; want %q", err, tc.want)
			}
		})
	}
}

func TestWriteAndDrift(t *testing.T) {
	dir := t.TempDir()
	files := map[string][]byte{"a.gen.go": []byte("// Code generated by mcpgen. DO NOT EDIT.\npackage api\n")}
	if err := Write(dir, files); err != nil {
		t.Fatal(err)
	}
	if err := Check(dir, files); err != nil {
		t.Fatal(err)
	}
	path := filepath.Join(dir, "a.gen.go")
	before, err := os.Stat(path)
	if err != nil {
		t.Fatal(err)
	}
	if err := Write(dir, files); err != nil {
		t.Fatal(err)
	}
	after, err := os.Stat(path)
	if err != nil {
		t.Fatal(err)
	}
	if !before.ModTime().Equal(after.ModTime()) {
		t.Fatal("unchanged file was rewritten")
	}
	if err := os.WriteFile(path, []byte("package handwritten\n"), 0644); err != nil {
		t.Fatal(err)
	}
	if err := Check(dir, files); err == nil {
		t.Fatal("drift was not detected")
	}
	files["0.gen.go"] = files["a.gen.go"]
	if err := Write(dir, files); err == nil {
		t.Fatal("handwritten file was overwritten")
	}
	if _, err := os.Stat(filepath.Join(dir, "0.gen.go")); !os.IsNotExist(err) {
		t.Fatal("ownership check wrote a partial package")
	}
}

func TestSchemaTypes(t *testing.T) {
	data := `mcp: "1"
info: {name: types, version: "1"}
tools:
  inspect:
    input:
      type: object
      required: [id]
      properties:
        id: {type: string}
        limit: {type: integer}
        ratio: {type: number}
        enabled: {type: boolean}
        mode: {$ref: '#/schemas/Mode'}
        codes:
          type: array
          items: {type: integer, enum: [1, 2]}
        entries:
          type: array
          items:
            type: object
            required: [name]
            properties:
              name: {type: string}
              matrix: {type: array, items: {type: array, items: {type: number}}}
    output: {$ref: '#/schemas/List'}
schemas:
  Mode: {type: boolean, enum: [true, false]}
  Kind: {type: string, enum: [a, b]}
  Count: {type: integer, enum: [1, 2]}
  Ratio: {type: number, enum: [0.5, 1]}
  List: {type: array, items: {$ref: '#/schemas/Kind'}}
  Alias: {$ref: '#/schemas/List'}
`
	doc, err := spec.Parse("types.yaml", []byte(data))
	if err != nil {
		t.Fatal(err)
	}
	files, err := Generate(doc, "typeapi")
	if err != nil {
		t.Fatal(err)
	}
	source := string(files["types.gen.go"]) + `
var _ string = InspectInput{}.ID
var _ *int64 = InspectInput{}.Limit
var _ *float64 = InspectInput{}.Ratio
var _ *bool = InspectInput{}.Enabled
var _ *Mode = InspectInput{}.Mode
var _ *[]InspectInputCodesItem = InspectInput{}.Codes
var _ *[]InspectInputEntriesItem = InspectInput{}.Entries
var _ *[][]float64 = InspectInputEntriesItem{}.Matrix
var _ []Kind = List{}
var _ Alias = List{}
var _ Mode = ModeTrue
var _ Count = CountValue1
var _ Ratio = RatioValue1
`
	fset := token.NewFileSet()
	parsed, err := parser.ParseFile(fset, "types.gen.go", source, 0)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := new(types.Config).Check("typeapi", fset, []*ast.File{parsed}, nil); err != nil {
		t.Fatal(err)
	}
}

func TestAddedToolRequiresOnlyHandler(t *testing.T) {
	data, err := os.ReadFile("../../example/mcp.yaml")
	if err != nil {
		t.Fatal(err)
	}
	added := `tools:
  delete_pet:
    description: Delete a pet.
    input:
      type: object
      additionalProperties: false
      required: [pet_id]
      properties:
        pet_id: {type: string, pattern: '^[0-9]+$'}
    output:
      type: object
      required: [deleted]
      properties:
        deleted: {type: boolean}
`
	doc, err := spec.Parse("mcp.yaml", []byte(strings.Replace(string(data), "tools:\n", added, 1)))
	if err != nil {
		t.Fatal(err)
	}
	files, err := Generate(doc, "mcpapi")
	if err != nil {
		t.Fatal(err)
	}
	dir := t.TempDir()
	if err := Write(filepath.Join(dir, "example", "internal", "mcpapi"), files); err != nil {
		t.Fatal(err)
	}
	for _, path := range []string{"go.mod", "go.sum", "example/internal/mcpserver/server.go", "example/internal/service/pets.go"} {
		content, err := os.ReadFile(filepath.Join("../..", path))
		if err != nil {
			t.Fatal(err)
		}
		dst := filepath.Join(dir, path)
		if err := os.MkdirAll(filepath.Dir(dst), 0755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(dst, content, 0644); err != nil {
			t.Fatal(err)
		}
	}
	ctx, cancel := context.WithTimeout(context.Background(), 90*time.Second)
	defer cancel()
	build := func() ([]byte, error) {
		cmd := exec.CommandContext(ctx, "go", "test", "-mod=readonly", "./...")
		cmd.Dir = dir
		cmd.Env = append(os.Environ(), "GOPROXY=off", "GOTOOLCHAIN=local")
		return cmd.CombinedOutput()
	}
	output, err := build()
	if err == nil || !strings.Contains(string(output), "missing method DeletePet") {
		t.Fatalf("expected missing method compile error; err=%v\n%s", err, output)
	}
	path := filepath.Join(dir, "example", "internal", "mcpserver", "server.go")
	f, err := os.OpenFile(path, os.O_APPEND|os.O_WRONLY, 0644)
	if err != nil {
		t.Fatal(err)
	}
	_, writeErr := f.WriteString(`
func (h *Handler) DeletePet(_ context.Context, input mcpapi.DeletePetInput) (mcpapi.DeletePetOutput, error) {
    return mcpapi.DeletePetOutput{Deleted: input.PetID == "1"}, nil
}
`)
	closeErr := f.Close()
	if writeErr != nil {
		t.Fatal(writeErr)
	}
	if closeErr != nil {
		t.Fatal(closeErr)
	}
	protocolTest := `package integration
import (
    "context"
    "encoding/json"
    "testing"
    "time"
    "github.com/modelcontextprotocol/go-sdk/mcp"
    "github.com/phaseant/mcpgen/example/internal/mcpapi"
    "github.com/phaseant/mcpgen/example/internal/mcpserver"
    "github.com/phaseant/mcpgen/example/internal/service"
)
func TestNewTool(t *testing.T) {
    ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
    defer cancel()
    server, err := mcpapi.NewServer(mcpserver.New(&service.Pets{}))
    if err != nil { t.Fatal(err) }
    st, ct := mcp.NewInMemoryTransports()
    ss, err := server.MCP().Connect(ctx, st, nil)
    if err != nil { t.Fatal(err) }; defer ss.Close()
    client := mcp.NewClient(&mcp.Implementation{Name: "test", Version: "1"}, nil)
    cs, err := client.Connect(ctx, ct, nil)
    if err != nil { t.Fatal(err) }; defer cs.Close()
    list, err := cs.ListTools(ctx, nil)
    if err != nil { t.Fatal(err) }
    found := false
    for _, tool := range list.Tools { if tool.Name == "delete_pet" { found = true } }
    if !found || len(list.Tools) != 5 { t.Fatalf("tools=%+v", list.Tools) }
    result, err := cs.CallTool(ctx, &mcp.CallToolParams{Name: "delete_pet", Arguments: map[string]any{"pet_id": "1"}})
    if err != nil || result.IsError { t.Fatalf("result=%+v err=%v", result, err) }
    data, err := json.Marshal(result.StructuredContent)
    if err != nil { t.Fatal(err) }
    var out mcpapi.DeletePetOutput
    if err := json.Unmarshal(data, &out); err != nil { t.Fatal(err) }
    if !out.Deleted || len(result.Content) != 1 { t.Fatalf("result=%+v", result) }
    result, err = cs.CallTool(ctx, &mcp.CallToolParams{Name: "delete_pet", Arguments: map[string]any{"pet_id": "invalid"}})
    if err != nil || !result.IsError { t.Fatalf("invalid arguments result=%+v err=%v", result, err) }
}
`
	if err := os.WriteFile(filepath.Join(dir, "example", "integration_test.go"), []byte(protocolTest), 0644); err != nil {
		t.Fatal(err)
	}
	output, err = build()
	if err != nil {
		t.Fatalf("adding only the handler method did not work: %v\n%s", err, output)
	}
}
