// Code generated by mcpgen. DO NOT EDIT.

package echoapi

import "context"

type Handler interface {
	Echo(context.Context, EchoInput) (EchoOutput, error)
}

type UnimplementedHandler struct{}

func (UnimplementedHandler) Echo(context.Context, EchoInput) (EchoOutput, error) {
	var zero EchoOutput
	return zero, ErrNotImplemented
}
