// Code generated by mcpgen. DO NOT EDIT.

package echoapi

import "encoding/json"

var schemaEchoInput = json.RawMessage("{\"additionalProperties\":false,\"properties\":{\"message\":{\"minLength\":1,\"type\":\"string\"}},\"required\":[\"message\"],\"type\":\"object\"}")
var schemaEchoOutput = json.RawMessage("{\"properties\":{\"message\":{\"type\":\"string\"}},\"required\":[\"message\"],\"type\":\"object\"}")
