// Code generated by mcpgen. DO NOT EDIT.

package echoapi

import "github.com/modelcontextprotocol/go-sdk/mcp"

var hintEchoDestructiveHint = false
var toolEcho = &mcp.Tool{Name: "echo", Title: "Echo", Description: "Echo a message.", Annotations: &mcp.ToolAnnotations{ReadOnlyHint: true, IdempotentHint: false, Title: "", DestructiveHint: &hintEchoDestructiveHint}, InputSchema: schemaEchoInput, OutputSchema: schemaEchoOutput}
